# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.system("pip install pyqt5")
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(820, 700)
        MainWindow.setMinimumSize(QtCore.QSize(820, 700))
        MainWindow.setMaximumSize(QtCore.QSize(820, 700))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enviar.setGeometry(QtCore.QRect(470, 350, 80, 30))
        self.btn_enviar.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_enviar.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_enviar.setFont(font)
        self.btn_enviar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_enviar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 255);\n"
"    color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover {\n"
"    color:  rgb(188, 188, 188);\n"
"    background-color: rgb(247, 10, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color:  rgb(188, 188, 188);\n"
"    background-color: rgb(170, 0, 255);\n"
"}")


        self.btn_enviar.setObjectName("btn_enviar")
        self.tb_user = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_user.setGeometry(QtCore.QRect(270, 240, 281, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_user.sizePolicy().hasHeightForWidth())
        self.tb_user.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tb_user.setFont(font)
        self.tb_user.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 150, 150);\n"
"padding: 5px;\n"
"border: 2px solid rgb(170, 0, 255)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(255, 0, 255)\n"
"}\n"
"QLineEdit:focus{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(255, 0, 255)\n"
"}\n"
"")
        self.tb_user.setMaxLength(50)
        self.tb_user.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.tb_user.setClearButtonEnabled(True)
        self.tb_user.setObjectName("tb_user")
        self.t_password = QtWidgets.QLineEdit(self.centralwidget)
        self.t_password.setGeometry(QtCore.QRect(270, 300, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.t_password.setFont(font)
        self.t_password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.t_password.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(150, 150, 150);\n"
"padding: 5px;\n"
"border: 2px solid rgb(170, 0, 255)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(255, 0, 255)\n"
"}\n"
"QLineEdit:focus{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(255, 0, 255)\n"
"}\n"
"")
        self.t_password.setMaxLength(16)
        self.t_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t_password.setClearButtonEnabled(True)
        self.t_password.setObjectName("t_password")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(350, 130, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_login.setFont(font)
        self.lbl_login.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lbl_login.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_login.setStyleSheet("QLabel{\n"
"    background: none;\n"
"    color: rgb(170, 0, 255);\n"
"}")
        self.lbl_login.setObjectName("lbl_login")
        self.cb_save = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_save.setGeometry(QtCore.QRect(270, 360, 70, 17))
        self.cb_save.setStyleSheet("color: rgb(255, 255, 255)")
        self.cb_save.setObjectName("cb_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculo de IMC - Login"))
        self.btn_enviar.setText(_translate("MainWindow", "ENVIAR"))
        self.tb_user.setPlaceholderText(_translate("MainWindow", "USER"))
        self.t_password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.lbl_login.setText(_translate("MainWindow", "Login"))
        self.cb_save.setText(_translate("MainWindow", "Save User"))
